#https://www.billboard.com/charts/tiktok-billboard-top-50/
#Week of October 28, 2023
tiktok_50 = {
        "My Love Mine All Mine" : "Mitski",
        "IDGAF" : "Drake Featuring Yeat",
        "Wicked" : "Future",
        "Real Love" : "Martin Garrix & Lloyiso",
        "This Wish" : "Ariana DeBose",
        "It Girl (Sped Up)" : "Aliyah's Interlude",
        "Steal The Show" : "Lauv",
        "What's Luv?" : "Fat Joe Featuring Ashanti",
        "Bando (Sped Up + Reverb)" : "bbygirl",
        "Paint The Town Red" : "Doja Cat",
        "Ick" : "Lay Bankz",
        "Wassup Gwayy" : "FamousSally & YB",
        "Barbie" : "JaidynAlexis",
        "Water" : "Tyla",
        "We Fell In Love In October" : "girl in red",
        "Greedy" : "Tate McRae",
        "My Life Breathe" : "Violette Levi",
        "BP - Sped Up" : "Summer Walker",
        "I Love You Hoe" : "Odetari & 9lives",
        "Gorgeous" : "Tee Grizzley, City Girls & Skilla Baby",
        "Rich Baby Daddy" : "Drake Featuring Sexyy Red & SZA",
        "Otra Vez" : "ProdMarvin",
        "SkeeYee" : "Sexyy Red",
        "Wop" : "J. Dash",
        "We Don't Talk About Bruno" : "Carolina Gaitan, Mauro Castillo, Adassa, Rhenzy Feliz, Diane Guerrero, Stephanie Beatriz & Encanto Cast",
        "Thunder/Young Dumb & Broke (Medley)" : "Imagine Dragons + Khalid",
        "White Tee" : "Summer Walker & NO1-NOAH",
        "What Was I Made For?" : "Billie Eilish",
        "Soak City (Do It)" : "310babii",
        "Sativa" : "Jhene Aiko Featuring Swae Lee Or Rae Sremmurd",
        "Drop It Like It's Hot" : "Snoop Dogg Featuring Pharrell",
        "Lil Boo Thang" : "Paul Russell",
        "MR. TAKE YA B*TCH" : "Lil Mabu & chriseanrock",
        "Agora Hills" : "Doja Cat",
        "Virginia Beach" : "Drake",
        "Fuck Up Yo Life (Sped Up Version)" : "Rucci",
        "Cruel Summer" : "Taylor Swift",
        "500lbs" : "Lil Tecca",
        "Wonder If U Care" : "flyingfish",
        "This Is Halloween" : "The Party Cats",
        "Spooky, Scary Skeletons (House VIP Remix)" : "Crystal Knives & Lex Allen",
        "My Dawg" : "Lil Baby",
        "The Good Life" : "OneRepublic",
        "Big Dick Randy" : "DigBar",
        "Low Life" : "Future Featuring The Weeknd",
        "Lollipop" : "Darell",
        "Handsome & Wealthy" : "Migos",
        "Ecstacy (Slowed)" : "SUICIDAL-IDOL",
        "Strangers" : "Kenya Grace",
        "Monaco" : "Bad Bunny",
}

#https://www.billboard.com/charts/hot-100/
#Week of October 28, 2023
billboard_50 = {
    "Cruel Summer" : "Taylor Swift",
    "Paint The Town Red" : "Doja Cat",
    "Snooze" : "SZA",
    "IDGAF" : "Drake Featuring Yeat",
    "Monaco" : "Bad Bunny",
    "I Remember Everything" : "Zach Bryan Featuring Kacey Musgraves",
    "Fast Car" : "Luke Combs",
    "First Person Shooter" : "Drake Featuring J. Cole",
    "Last Night" : "Morgan Wallen",
    "Thinkin' Bout Me" : "Morgan Wallen",
    "Fukumean" : "Gunna",
    "Vampire" : "Olivia Rodrigo",
    "Dance The Night" : "Dua Lipa",
    "Fina" : "Bad Bunny & Young Miko",
    "Virginia Beach" : "Drake",
    "Rich Baby Daddy" : "Drake Featuring Sexyy Red & SZA",
    "Greedy" : "Tate McRae",
    "Flowers" : "Miley Cyrus",
    "Barbie World" : "Nicki Minaj & Ice Spice With Aqua",
    "Perro Negro" : "Bad Bunny & Feid",
    "Slime You Out" : "Drake Featuring SZA",
    "Nadie Sabe" : "Bad Bunny",
    "Need A Favor" : "Jelly Roll",
    "Hibiki" : "Bad Bunny & Mora",
    "Anti-Hero" : "Taylor Swift",
    "Used To Be Young" : "Miley Cyrus",
    "All My Life" : "Lil Durk Featuring J. Cole",
    "Mr. October" : "Bad Bunny",
    "Religiously" : "Bailey Zimmerman",
    "Cybertruck" : "Bad Bunny",
    "Watermelon Moonshine" : "Lainey Wilson",
    "Telefono Nuevo" : "Bad Bunny & Luar La L",
    "Dial Drunk" : "Noah Kahan With Post Malone",
    "Baby Nueva" : "Bad Bunny",
    "My Love Mine All Mine" : "Mitski",
    "Kill Bill" : "SZA",
    "Save Me" : "Jelly Roll With Lainey Wilson",
    "Seda" : "Bad Bunny & Bryant Myers",
    "Good Good" : "Usher, Summer Walker & 21 Savage",
    "What Was I Made For?" : "Billie Eilish",
    "What It Is (Block Boy)" : "Doechii Featuring Kodak Black",
    "Bad Idea Right?" : "Olivia Rodrigo",
    "White Horse" : "Chris Stapleton",
    "Creepin'" : "Metro Boomin, The Weeknd & 21 Savage",
    "Daylight" : "David Kushner",
    "Water" : "Tyla",
    "Un Preview" : "Bad Bunny",
    "Say My Grace" : "Offset Featuring Travis Scott",
    "Gently" : "Drake Featuring Bad Bunny",
    "Try That In A Small Town" : "Jason Aldean",
}
