    name: Autograding Workflow

    on: [push]

    jobs:
      build:
        name: Autograding
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - uses: CS3235test/dummy-autograding@v1
            id: autograding
          - uses: CS3235test/grade-report@v2
            with:
              score: "${{ steps.autograding.outputs.score }}"

